---
deployment:
  tasks:
    - export DEPLOYPATH=../
    - npm install
    - npm run build
    - /bin/rm -rf $DEPLOYPATH/index.html $DEPLOYPATH/assets
    - /bin/cp -R dist/* $DEPLOYPATH
    - /bin/cp public/.htaccess $DEPLOYPATH/.htaccess
    - /bin/ls -la $DEPLOYPATH
